export default [
  {
    id: 72,
    title: "Arriving School and Smiling Wild",
    date: "20 October 2022",
    location: "School, DLine, PH",
    discription: "Having fun going to school, though arriving late 😋",
    imgUrl: "/images/oct26.jpg",
  },
  {
    id: 71,
    title: "Arriving School and Smiling Wild",
    date: "20 October 2022",
    location: "School, DLine, PH",
    discription: "Having fun going to school, though arriving late 😋",
    imgUrl: "/images/oct20.jpg",
  },
  {
    id: 70,
    title: "Arriving School",
    date: "20 October 2022",
    location: "School, DLine, PH",
    discription: "I'm Enjoying this school thingy",
    imgUrl: "/images/oct20b.jpg",
  },
  {
    id: 69,
    title: "I and Dad Chilling 🥳",
    date: "15 October 2022",
    location: "Home, DLine, PH",
    discription: "Judt goofing at home",
    imgUrl: "/images/oct15.jpg",
  },
  {
    id: 68,
    title: "I've Got Balloons Today -My Birthday🎉🥳",
    date: "13 October 2022",
    location: "RedKarpet, GRA, PH",
    discription: "I am a Year Old!",
    imgUrl: "/images/Bd1.jpg",
  },
  {
    id: 67,
    title: "Still My Birthday Things 🥳🎈🥂🍾",
    date: "13 October 2022",
    location: "RedKarpert, GRA, PH",
    discription: "I am a Year Old!",
    imgUrl: "/images/Bd2.jpg",
  },
  {
    id: 66,
    title: "Home, Ready For School",
    date: "23 September 2022",
    location: "Home, D/Line, PH",
    discription: "Like any other day!",
    imgUrl: "/images/23 Sep.jpg",
  },
  {
    id: 65,
    title: "Funny People, see what they did to me",
    date: "11 September 2022",
    location: "Home, D/Line, PH",
    discription: "Is this playing?!",
    imgUrl: "/images/s11.jpg",
  },
  {
    id: 64,
    title: "Flying High in School 🤗",
    date: "8 September 2022",
    location: "D/Line, PH",
    discription: "Got to Enjoy School",
    imgUrl: "/images/s8b.jpg",
  },
  {
    id: 63,
    title: "Arriving School In Style 🤗",
    date: "8 September 2022",
    location: "D/Line, PH",
    discription: "School get me thinking",
    imgUrl: "/images/s8a.jpg",
  },
  {
    id: 62,
    title: "New Week and Back to School 🤗",
    date: "5 September 2022",
    location: "D/Line, PH",
    discription: "School",
    imgUrl: "/images/s5b.jpg",
  },
  {
    id: 61,
    title: "Goofing around with Dad",
    date: "5 September 2022",
    location: "Home, D/Line, PH",
    discription: "Home is better",
    imgUrl: "/images/s5a.jpg",
  },
  {
    id: 611,
    title: "Goofing around with Dad",
    date: "2 September 2022",
    location: "Home, D/Line, PH",
    discription: "Home is Always better",
    imgUrl: "/images/s2.jpg",
  },
  {
    id: 60,
    title: "New Week and Back to School 🤗",
    date: "21 August 2022",
    location: "D/Line, PH",
    discription: "School",
    imgUrl: "/images/a22.jpg",
  },
  {
    id: 59,
    title: "I Got Swag 🤗",
    date: "21 August 2022",
    location: "D/Line, PH",
    discription: "Outing",
    imgUrl: "/images/a21.jpg",
  },
  {
    id: 58,
    title: "I Got Swag 🤗",
    date: "21 August 2022",
    location: "Home, D/Line, PH",
    discription: "My Mummy is doing well",
    imgUrl: "/images/bestme.png",
  },
  {
    id: 57,
    title: "Getting Ready to Swag 🤗",
    date: "21 August 2022",
    location: "Home, D/Line, PH",
    discription: "Arranging myself well ",
    imgUrl: "/images/bestme1.png",
  },
  {
    id: 56,
    title: "Making me wear over size shirt 🤗",
    date: "17 August 2022",
    location: "Outside, School, D/Line, PH",
    discription: "Got wounded on my face day before yesterday",
    imgUrl: "/images/17.png",
  },
  {
    id: 55,
    title: "I've got to try modelling",
    date: "16 August 2022",
    location: "Outside, School, D/Line, PH",
    discription: "Me, I and myself",
    imgUrl: "/images/16.png",
  },
  {
    id: 54,
    title: "How we roll",
    date: "15 August 2022",
    location: "Outside, School, D/Line, PH",
    discription: "Me, I and myself",
    imgUrl: "/images/15.png",
  },
  {
    id: 531,
    title: "Today I'm 10-Months old",
    date: "13 August 2022",
    location: "Home, D/Line, PH",
    discription: "Me goofing around",
    imgUrl: "/images/bdb.png",
  },
  {
    id: 53,
    title: "10-Months me with mum",
    date: "13 August 2022",
    location: "Outside, Home, D/Line, PH",
    discription: "Me and my mummy",
    imgUrl: "/images/bd.png",
  },
  {
    id: 52,
    title: "I can do the 'Boga Dance'",
    date: "12 August 2022",
    location: "Peace Ville Schools, D/Line, PH",
    discription: "My arrival to school",
    imgUrl: "/images/if7.png",
  },
  {
    id: 51,
    title: "The Head Boy arriving school",
    date: "11 August 2022",
    location: "Peace Ville, D/Line, PH",
    discription: "My arrival to school",
    imgUrl: "/images/if5.png",
  },
  {
    id: 50,
    title: "Can I go to class now?!",
    date: "11 August 2022",
    location: "Peace Ville, D/Line, PH",
    discription: "About to go to class",
    imgUrl: "/images/if6.png",
  },
  {
    id: 49,
    title: "Fresh day & fresh me at school",
    date: "11 August 2022",
    location: "Peace Ville, D/Line, PH",
    discription: "My arrival to school",
    imgUrl: "/images/if3.png",
  },
  {
    id: 48,
    title: "I see you",
    date: "10 August 2022",
    location: "Home, D/Line, PH",
    discription: "Just waking up and ready to play",
    imgUrl: "/images/if1.png",
  },
  {
    id: 47,
    title: "Play time",
    date: "10 August 2022",
    location: "home, D/Line, PH",
    discription: "Phone call play",
    imgUrl: "/images/if2.png",
  },
  {
    id: 46,
    title: "At Ebuka's JSS3 Graduation",
    date: "4 August 2022",
    location: "Meekfield Academy, D/Line, PH",
    discription: "Ebuka is now going to be a senior student 🎉🍾",
    imgUrl: "/images/ebk.png",
  },
  {
    id: 45,
    title: "Ebuka's Graduation Day",
    date: "4 August 2022",
    location: "Meekfield, D/Line, PH",
    discription: "why were they smiling?!",
    imgUrl: "/images/gg.png",
  },
  {
    id: 44,
    title: "Graduation Day",
    date: "4 August 2022",
    location: "Meekfield, D/Line, PH",
    discription: "Ebuka please carry me well or drop me 😋",
    imgUrl: "/images/gg2.png",
  },
  {
    id: 43,
    title: "I'm beginning to walk",
    date: "3 August 2022",
    location: "My school, D/Line, PH",
    discription: "I'm trying, even as my leg hurts",
    imgUrl: "/images/wl.png",
  },
  {
    id: 42,
    title: "Hot water poured on my leg",
    date: "1 August 2022",
    location: "Front of home, D/Line, PH",
    discription: "This happened 2 days ago, it hurts sometimes",
    imgUrl: "/images/wa2.png",
  },
  {
    id: 41,
    title: "Chilling with Dad, Mum & Ebuka",
    date: "27 July 2022",
    location: "Outside, Home, D/Line, PH",
    discription: "Guess we're enjoying. Needed Dad's face cap",
    imgUrl: "/images/a.png",
  },
  {
    id: 39,
    title: "With Dad, 8-days after 9months",
    date: "21 July 2022",
    location: "Home, D/Line, PH",
    discription: "Just chilling",
    imgUrl: "/images/hm3.png",
  },
  {
    id: 38,
    title: "I can stand, 8months going to 9",
    date: "01 July 2022",
    location: "Home, D/Line, PH",
    discription: "Guess I'm enjoying it",
    imgUrl: "/images/st.png",
  },
  {
    id: 37,
    title: "In school, 8 days after 8 months",
    date: "21 June 2022",
    location: "School, D/Line, PH",
    discription: "Guess I'm enjoying it; as the youngest Prof.",
    imgUrl: "/images/sc1.png",
  },
  {
    id: 36,
    title: "Daddy & Mummy took me to school",
    date: "21 June 2022",
    location: "School, D/Line, PH",
    discription: "Not sure what to feel",
    imgUrl: "/images/sc.png",
  },
  {
    id: 35,
    title: "Mummy dressing me for school",
    date: "21 June 2022",
    location: "Home, D/Line, PH",
    discription: "Not sure how to feel here",
    imgUrl: "/images/pf.png",
  },
  {
    id: 34,
    title: "6-month old me; got no worries",
    date: "13 April 2022",
    location: "Home, D/Line, PH",
    discription: "I'm 6-month today 🤣🍾🥂",
    imgUrl: "/images/ju.png",
  },
  {
    id: 33,
    title: "I've got swag",
    date: "13 April 2022",
    location: "Enroute, Aba-PH Road, PH",
    discription: "My Mummy and I, going to office",
    imgUrl: "/images/ss.png",
  },
  {
    id: 32,
    title: "I've got style",
    date: "13 April 2022",
    location: "Enroute, Aba-PH Road, PH",
    discription: "Heading to Mummy's office",
    imgUrl: "/images/sd.png",
  },
  {
    id: 31,
    title: "Looking up in confidence",
    date: "16 March 2022",
    location: "Home, D/Line, PH",
    discription: "Crawling already, and learning to pay attention",
    imgUrl: "/images/bh.png",
  },
  {
    id: 30,
    title: "5-month old me: guess I can sing",
    date: "13 March 2022",
    location: "Home, D/Line, PH",
    discription: "I'm 5-month today and I've got no troubles 🍾🥂",
    imgUrl: "/images/de.png",
  },

  {
    id: 29,
    title: "Curious me",
    date: "20 Feb. 2022",
    location: "Home, D/Line, PH",
    discription: "I'm 8 days past 4months",
    imgUrl: "/images/bvv.png",
  },
  {
    id: 28,
    title: "I can now sit 😂 [@3months]",
    date: "22 Jan. 2022",
    location: "Home, D/Line, PH",
    discription: "The New Year began with me sitting",
    imgUrl: "/images/bn.png",
  },
  {
    id: 27,
    title: "I've not fogotten how to lie-down 😄",
    date: "22 Jan. 2022",
    location: "Home, D/Line, PH",
    discription: "Having fun",
    imgUrl: "/images/dr.png",
  },
  {
    id: 26,
    title: "Daddy, Mummy, and I",
    date: "31 Dec. 2021",
    location: "Pleasure Pack, Arena, PH",
    discription: "Last day of 2021, we'd to go chilling",
    imgUrl: "/images/po.png",
  },
  {
    id: 25,
    title: "Me, I and Myself Chilling",
    date: "24 Dec. 2021",
    location: "Home, D/Line, PH",
    discription: "Well feed and chilling",
    imgUrl: "/images/fd.png",
  },
  {
    id: 24,
    title: "Daddy, Ebuka, Chi, Mummy, and I",
    date: "23 Dec. 2021",
    location: "Pleasure Pack, Movie Zone, PH",
    discription: "Fun time, but me sleeping 😴",
    imgUrl: "/images/ed.png",
  },
  {
    id: 23,
    title: "Daddy, Mummy, and I",
    date: "23 Dec. 2021",
    location: "Pleasure Pack, PH",
    discription: "Fun time, but why hidding me away in the carrier?!",
    imgUrl: "/images/bb.png",
  },
  {
    id: 22,
    title: "Daddy, Mummy, Chi, and I",
    date: "23 Dec. 2021",
    location: "Pleasure Pack, PH",
    discription: "'but what kind of playing is this inside water?!'",
    imgUrl: "/images/qw.png",
  },
  {
    id: 21,
    title: "Water boating",
    date: "23 Dec. 2021",
    location: "Pleasure Pack, PH",
    discription: "I'm enjoying it though. I'm 2months and 10 days",
    imgUrl: "/images/vb.png",
  },
  {
    id: 20,
    title: "Daddy, Mum, Chi, Ebuka and I",
    date: "23 Dec. 2021",
    location: "Pleasure Pack, PH",
    discription: "Fun time, but hidden away in the carrier",
    imgUrl: "/images/bv.png",
  },
  {
    id: 19 / 20,
    title: "I've got swag 🧢",
    date: "22 Dec. 2021",
    location: "At home. D/Line, PH",
    discription: "I'm past 2 months old now🤭",
    imgUrl: "/images/d2.jpg",
  },
  {
    id: 19,
    title: "At Daddy's office 👼🏼",
    date: "11 Dec. 2021",
    location: "Outing time",
    discription: "I'm past 2 months old now🤭",
    imgUrl: "/images/q1.png",
  },
  {
    id: 18,
    title: "Happy me 😁",
    date: "11 Dec. 2021",
    location: "At home",
    discription: "I'm 2 days to being 2months old 🤭",
    imgUrl: "/images/ew.png",
  },
  {
    id: 17,
    title: "Me exploring 👼🏼",
    date: "01 Dec. 2021",
    location: "At home",
    discription: "Me happy just after waking 🤭",
    imgUrl: "/images/wc.png",
  },
  {
    id: 16,
    title: "My Mummy & I goofing around 🎭",
    date: "18 Nov. 2021",
    location: "At home",
    discription: "Me happy just after eating 🤭",
    imgUrl: "/images/pl.png",
  },
  {
    id: 15,
    title: "All I had to do was sleep 👼🏼",
    date: "17 Nov. 2021",
    location: "At home",
    discription: "I'm just over a month old 🤭",
    imgUrl: "/images/qa.png",
  },
  {
    id: 14,
    title: "Curious me exploring daddy 👼🏼",
    date: "31 Oct. 2021",
    location: "At home with my Daddy",
    discription: "My Daddy and I",
    imgUrl: "/images/IMG_6.jpg",
  },
  {
    id: 13,
    title: "Curious me not posing for selfie 🧒🏻",
    date: "31 Oct. 2021",
    location: "At home with my Daddy",
    discription: "My Daddy and I",
    imgUrl: "/images/IMG_4.png",
  },
  {
    id: 12,
    title: "All I had to do was sleep 👼🏼",
    date: "22 Oct. 2021",
    location: "Home, D/line, PH",
    discription: "Tiny me sleeping",
    imgUrl: "/images/avb.png",
  },
  {
    id: 11,
    title: "Three days after I was born 👼🏼",
    date: "16 Oct. 2021",
    location: "Home, D/line, PH",
    discription: "Tiny me sleeping",
    imgUrl: "/images/IMG_2.jpg",
  },
  {
    id: 10,
    title: "The day I was born 👼🏼",
    date: "13 Oct. 2021",
    location: "RS Teaching Hospital, Tiny me sleeping",
    discription: "I weighed about 3.6kg",
    imgUrl: "/images/IMG_1.jpg",
  },
  {
    id: 9,
    title: "Mum carrying me in the womb",
    date: "29 Aug. 2021",
    location: "Pleasur pack, Airforce, PH",
    discription: "Man help Ebuka play CGI, mum watches",
    imgUrl: "/images/abe.png",
  },
  {
    id: 8,
    title: "My parents and their friends",
    date: "19 June 2021",
    location: "After CM, Jevinik, GRA, PH",
    discription: "Mum and Dad's Court Marriage",
    imgUrl: "/images/aa3.png",
  },
  {
    id: 7,
    title: "My parents and their friends",
    date: "19 June 2021",
    location: "Marriage Registry, D/Line, PH",
    discription: "Mum and Dad's Court Marriage",
    imgUrl: "/images/2a.png",
  },
  {
    id: 6,
    title: "My parents and friends",
    date: "19 June 2021",
    location: "Marriage Registry, D/Line, PH",
    discription: "My Mum and Dad's Court Marriage",
    imgUrl: "/images/1c.png",
  },
  {
    id: 5,
    title: "My parents",
    date: "19 June 2021",
    location: "Marriage Registry, D/Line, PH",
    discription: "Mum and Dad's Court Marriage",
    imgUrl: "/images/1d.png",
  },
  {
    id: 4,
    title: "My parents goofing around",
    date: "10 Dec. 2020",
    location: "Eatery around Garrision, PH",
    discription: "having fun not even waitng me 🤭😮",
    imgUrl: "/images/ab4.png",
  },
  {
    id: 3,
    title: "My parents during their TM",
    date: "05 Sept. 2020",
    location: "Ihie, Amasiri, Afikpo",
    discription: "Mum and Dad's Traditional Marriage",
    imgUrl: "/images/1a.png",
  },
  {
    id: 2,
    title: "My parents and grand-parents",
    date: "05 Sept. 2020",
    location: "Ihie, Amasiri, Afikpo",
    discription: "During my Mum and Dad's TM",
    imgUrl: "/images/1b.png",
  },
  {
    id: 1,
    title: "My Parents and how it all started",
    date: "27th May 2020",
    location: "Oroworukwo, D/Line, Port Harcourt",
    discription: "When they were dating",
    imgUrl: "/images/aa.png",
  }
]